name: shelf_test_handler
version: 2.0.1-dev
description: A Shelf handler that makes it easy to test HTTP interactions.
homepage: https://github.com/dart-lang/shelf_test_handler

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http_multi_server: ^3.0.0
  shelf: ^1.0.0
  test: ^1.16.0

dev_dependencies:
  http: ^0.13.0
  pedantic: ^1.10.0
  shelf_web_socket: ^1.0.0

dependency_overrides:
  http_multi_server: ^3.0.0
  shelf_web_socket: ^1.0.0
  test: ^1.16.0
