name: shelf_test_handler
version: 1.0.4-dev
description: A Shelf handler that makes it easy to test HTTP interactions.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/shelf_test_handler

environment:
  sdk: '>=2.8.4 <3.0.0'

dependencies:
  http_multi_server: ^2.0.0
  shelf: ">=0.6.0 <0.8.0"
  test: ^1.0.0

dev_dependencies:
  http: ^0.12.0
  pedantic: ^1.4.0
  shelf_web_socket: ^0.2.1
